@startuml
start
    while (true)
        while (input files available?) is (yes)
          :read input file;
          :publish line by line;
note left
take into consideration
the topic settings 
(e.g. batching)
end note
        endwhile (no)
        :sleep 60 sec;
    endwhile
stop
@enduml
